"""Pydantic models for ``sillo.toml``.

The manifest is the authoritative description of a generated project: what the
application is, which features are switched on, and how to run it. Every other
subsystem reads it rather than sniffing the filesystem, so ``add``, ``remove``,
``dev``, ``doctor`` and ``upgrade`` all agree on the project's shape.

The models are permissive about unknown keys on purpose. A project generated by
a newer Sillo Start, or extended by a plugin that owns its own section, must
still load in an older tool rather than failing validation.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from ..utils.naming import is_valid_project_name, package_name_for
from .defaults import (
    DEFAULT_BACKEND_PORT,
    DEFAULT_FRONTEND_PORT,
    ORM,
    SILLO_VERSION_SPEC,
    AppType,
    AuthStrategy,
    CacheDriver,
    DatabaseDriver,
    FrontendPackageManager,
    InertiaAdapter,
    MailDriver,
    PythonPackageManager,
    QueueDriver,
    SessionDriver,
    StorageDriver,
)

#: Manifest schema version. Bumped when a change needs migration on upgrade.
MANIFEST_VERSION = 1


class Section(BaseModel):
    """Base for every manifest section.

    ``extra="allow"`` is what lets a plugin add keys to a section, and lets an
    older Sillo Start read a manifest written by a newer one without dropping
    the keys it does not understand.
    """

    model_config = ConfigDict(extra="allow", validate_assignment=True, use_enum_values=True)


class ProjectSection(Section):
    """Identity of the project itself."""

    name: str = Field(description="Project name, also the directory name.")
    version: str = Field(default="0.1.0", description="Application version.")
    description: str = Field(default="", description="One-line project summary.")
    python: str = Field(default=">=3.11", description="Required Python range.")
    sillo_version: str = Field(
        default=SILLO_VERSION_SPEC,
        description="Version specifier for the sillo-framework dependency.",
    )
    package: str = Field(
        default="",
        description="Importable package name. Derived from the project name when blank.",
    )
    manifest_version: int = Field(
        default=MANIFEST_VERSION,
        description="Manifest schema version, used by `sillo-start upgrade`.",
    )
    created_with: str = Field(
        default="",
        description="Sillo Start version that generated the project.",
    )

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value: str) -> str:
        if not is_valid_project_name(value):
            raise ValueError(
                f"'{value}' is not a valid project name. Use a letter followed by "
                "letters, digits, dots, dashes or underscores."
            )
        return value

    @model_validator(mode="after")
    def _derive_package(self) -> ProjectSection:
        if not self.package:
            # Assigning through object.__setattr__ avoids re-triggering
            # validate_assignment, which would recurse through this validator.
            object.__setattr__(self, "package", package_name_for(self.name))
        return self


class ApplicationSection(Section):
    """How the application is shaped and launched."""

    type: AppType = Field(default=AppType.API)
    entrypoint: str = Field(
        default="app.main:app",
        description="ASGI entrypoint in `module:attribute` form.",
    )
    host: str = Field(default="127.0.0.1")
    port: int = Field(default=DEFAULT_BACKEND_PORT, ge=1, le=65535)


class DatabaseSection(Section):
    """Database connection and ORM configuration."""

    enabled: bool = False
    driver: DatabaseDriver = DatabaseDriver.NONE
    orm: ORM = ORM.NONE
    migrations_path: str = Field(default="database/migrations")
    models_module: str = Field(
        default="database.models",
        description="Dotted module Record scans for models.",
    )

    @property
    def migrations_module(self) -> str:
        """``migrations_path`` as a dotted module path.

        Tortoise locates migrations by import, not by directory, so the app
        config needs the module form of the same location.
        """
        return self.migrations_path.strip("/").replace("/", ".")

    @model_validator(mode="after")
    def _coherent(self) -> DatabaseSection:
        """Keep ``enabled`` and ``driver`` from contradicting each other."""
        if self.enabled and self.driver == DatabaseDriver.NONE:
            object.__setattr__(self, "driver", DatabaseDriver.SQLITE)
        if not self.enabled:
            object.__setattr__(self, "driver", DatabaseDriver.NONE)
            object.__setattr__(self, "orm", ORM.NONE)
        return self


class AuthSection(Section):
    """Authentication feature switches."""

    enabled: bool = False
    strategy: AuthStrategy = AuthStrategy.NONE
    user_model: str = Field(
        default="database.models.user.User",
        description="Dotted path to the project's user model.",
    )
    registration: bool = True
    login: bool = True
    logout: bool = True
    password_reset: bool = False
    email_verification: bool = False
    remember_me: bool = False
    middleware: bool = True
    routes: bool = True
    service_layer: bool = True
    tests: bool = True

    @model_validator(mode="after")
    def _coherent(self) -> AuthSection:
        """Keep the strategy consistent with whether auth is on at all.

        The sub-switches are deliberately left alone. Zeroing them here would
        be destructive: ``enabled`` is flipped on after construction by
        blueprints and by the admin's implications, and the switches would
        have already been cleared by the first validation pass with no way to
        tell a real ``registration = false`` from a side effect. Consumers ask
        for ``auth.enabled and auth.routes`` instead.
        """
        if not self.enabled:
            object.__setattr__(self, "strategy", AuthStrategy.NONE)
        elif self.strategy == AuthStrategy.NONE:
            object.__setattr__(self, "strategy", AuthStrategy.SESSION)
        return self


class AuthorizationSection(Section):
    """Roles, permissions and policy scaffolding."""

    enabled: bool = False
    roles: bool = False
    permissions: bool = False
    policies: bool = False
    guards: bool = False
    ownership: bool = False
    route_level: bool = False
    model_level: bool = False


class AdminSection(Section):
    """Sillo admin panel configuration."""

    enabled: bool = False
    prefix: str = Field(default="/admin")
    title: str = Field(default="")
    user_management: bool = True
    role_management: bool = False

    @field_validator("prefix")
    @classmethod
    def _normalise_prefix(cls, value: str) -> str:
        value = "/" + value.strip("/")
        return value.rstrip("/") or "/admin"


class InertiaSection(Section):
    """Inertia.js integration and the frontend project it drives."""

    enabled: bool = False
    adapter: InertiaAdapter = InertiaAdapter.REACT
    frontend_path: str = Field(default="frontend")
    root_view: str = Field(default="templates/app.html")
    package_manager: FrontendPackageManager = FrontendPackageManager.NPM
    port: int = Field(default=DEFAULT_FRONTEND_PORT, ge=1, le=65535)
    typescript: bool = True
    ssr: bool = False


class QueueSection(Section):
    """Background job processing."""

    enabled: bool = False
    driver: QueueDriver = QueueDriver.NONE
    name: str = Field(default="default", description="Default queue name.")
    concurrency: int = Field(default=4, ge=1, le=256)

    @model_validator(mode="after")
    def _coherent(self) -> QueueSection:
        if not self.enabled:
            object.__setattr__(self, "driver", QueueDriver.NONE)
        elif self.driver == QueueDriver.NONE:
            object.__setattr__(self, "driver", QueueDriver.MEMORY)
        return self


class SchedulerSection(Section):
    """Cron-style scheduled tasks."""

    enabled: bool = False
    tasks_module: str = Field(default="app.tasks")


class CacheSection(Section):
    enabled: bool = False
    driver: CacheDriver = CacheDriver.NONE


class SessionSection(Section):
    enabled: bool = False
    driver: SessionDriver = SessionDriver.COOKIE
    cookie_name: str = Field(default="session_id")
    lifetime: int = Field(default=86400, ge=60, description="Session lifetime in seconds.")


class MailSection(Section):
    enabled: bool = False
    driver: MailDriver = MailDriver.NONE


class StorageSection(Section):
    enabled: bool = False
    driver: StorageDriver = StorageDriver.NONE
    path: str = Field(default="storage/app")


class ApiSection(Section):
    """Cross-cutting API concerns."""

    enabled: bool = True
    openapi: bool = True
    versioning: bool = False
    prefix: str = Field(default="/api")
    pagination: bool = False
    rate_limiting: bool = False
    cors: bool = False
    csrf: bool = False
    request_id: bool = False
    structured_logging: bool = False
    error_handling: bool = True
    health_checks: bool = True


class ToolingSection(Section):
    """Developer tooling written into the project."""

    ruff: bool = True
    mypy: bool = False
    pytest: bool = True
    coverage: bool = False
    pre_commit: bool = False
    docker: bool = False
    compose: bool = False
    github_actions: bool = False
    makefile: bool = False
    taskfile: bool = False
    editorconfig: bool = True
    package_manager: PythonPackageManager = PythonPackageManager.UV


class PackagesSection(Section):
    """Enabled Sillo package groups."""

    groups: list[str] = Field(default_factory=list)

    @field_validator("groups")
    @classmethod
    def _dedupe(cls, value: list[str]) -> list[str]:
        """Drop duplicates while preserving install order."""
        seen: set[str] = set()
        ordered: list[str] = []
        for name in value:
            if name not in seen:
                seen.add(name)
                ordered.append(name)
        return ordered


class DevelopmentSection(Section):
    """Commands the orchestrator runs for ``sillo-start dev``.

    These are stored as strings so a developer can edit them without touching
    Sillo Start. They default to real, existing commands: the framework ships
    no CLI of its own, so the backend runs under uvicorn and the worker and
    scheduler run generated scripts.
    """

    backend_command: str = Field(default="uvicorn app.main:app --reload")
    frontend_command: str = Field(default="")
    worker_command: str = Field(default="")
    scheduler_command: str = Field(default="")
    extra_services: dict[str, str] = Field(default_factory=dict)


class SilloManifest(BaseModel):
    """The whole of ``sillo.toml``."""

    model_config = ConfigDict(extra="allow", validate_assignment=True)

    project: ProjectSection
    application: ApplicationSection = Field(default_factory=ApplicationSection)
    database: DatabaseSection = Field(default_factory=DatabaseSection)
    auth: AuthSection = Field(default_factory=AuthSection)
    authorization: AuthorizationSection = Field(default_factory=AuthorizationSection)
    admin: AdminSection = Field(default_factory=AdminSection)
    inertia: InertiaSection = Field(default_factory=InertiaSection)
    queue: QueueSection = Field(default_factory=QueueSection)
    scheduler: SchedulerSection = Field(default_factory=SchedulerSection)
    cache: CacheSection = Field(default_factory=CacheSection)
    session: SessionSection = Field(default_factory=SessionSection)
    mail: MailSection = Field(default_factory=MailSection)
    storage: StorageSection = Field(default_factory=StorageSection)
    api: ApiSection = Field(default_factory=ApiSection)
    tooling: ToolingSection = Field(default_factory=ToolingSection)
    packages: PackagesSection = Field(default_factory=PackagesSection)
    development: DevelopmentSection = Field(default_factory=DevelopmentSection)

    @model_validator(mode="after")
    def _admin_implies_sessions(self) -> SilloManifest:
        """Turn sessions on whenever the admin panel is enabled.

        The admin's default backend (``sillo.admin.auth.SessionAuth``) reads
        and writes ``request.session``; with no session middleware installed
        ``getattr(request, "session", None)`` is None, so ``authenticate``
        always returns False. The login form then appears to accept the
        password and bounces straight back to itself, forever, with nothing
        logged — so this is recorded in the manifest rather than papered over
        in the template, keeping sillo.toml an honest description of the app.
        """
        if self.admin.enabled and not self.session.enabled:
            object.__setattr__(self.session, "enabled", True)
        return self

    # -- convenience ----------------------------------------------------

    @property
    def name(self) -> str:
        """The project name."""
        return self.project.name

    @property
    def package(self) -> str:
        """The importable package name."""
        return self.project.package

    @property
    def uses_record(self) -> bool:
        """Whether the Record ORM is configured."""
        return self.database.enabled and self.database.orm == ORM.RECORD

    @property
    def uses_sessions(self) -> bool:
        """Whether the app needs session middleware installed.

        Derived rather than read straight off ``session.enabled`` because the
        admin panel requires sessions whether or not the operator asked for
        them, and blueprints flip ``admin.enabled`` after the manifest has been
        validated — so the manifest validator alone would miss those.
        """
        return self.session.enabled or self.admin.enabled

    @property
    def needs_redis(self) -> bool:
        """Whether any enabled feature requires a Redis server."""
        return (
            (self.queue.enabled and self.queue.driver == QueueDriver.REDIS)
            or (self.cache.enabled and self.cache.driver == CacheDriver.REDIS)
            or (self.session.enabled and self.session.driver == SessionDriver.REDIS)
        )

    @property
    def needs_web_routes(self) -> bool:
        """Whether a browser-facing router should be generated.

        True for anything that serves pages: an Inertia frontend renders
        through a web router, and a project without an API surface has nothing
        else to route with.
        """
        return self.inertia.enabled or not self.api.enabled

    @property
    def needs_database_server(self) -> bool:
        """Whether the database runs as a separate server process."""
        return self.database.enabled and self.database.driver in (
            DatabaseDriver.POSTGRES,
            DatabaseDriver.MYSQL,
        )

    def has_group(self, group: str) -> bool:
        """Report whether a package group is enabled."""
        return group in self.packages.groups

    def add_group(self, group: str) -> bool:
        """Enable a package group.

        Returns:
            True when the group was newly added.
        """
        if group in self.packages.groups:
            return False
        self.packages.groups = [*self.packages.groups, group]
        return True

    def remove_group(self, group: str) -> bool:
        """Disable a package group.

        Returns:
            True when the group was present and removed.
        """
        if group not in self.packages.groups:
            return False
        self.packages.groups = [name for name in self.packages.groups if name != group]
        return True

    def to_dict(self) -> dict[str, Any]:
        """Serialise for TOML writing, with enums flattened to their values."""
        return self.model_dump(mode="json", exclude_none=True)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> SilloManifest:
        """Build a manifest from parsed TOML data."""
        return cls.model_validate(data)
